[package]
name = "RustTask"
version = "0.1.0"
authors = ["Sebastian Kaźmierczak <sebastian.kazm@gmail.com>"]
edition = "2018"

[dependencies.chrono]
version = "0.4.10"

[dependencies.csv]
version = "1.1.3"

[dependencies.json]
version = "0.12.1"
